name: MDC Release

on:
  schedule:
    # Runs on 1st day of every month
    # See https://crontab.guru/#0_0_1_*_*
    - cron: '0 0 1 * *'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          npm install
      - name: Build packages
        run: |
          npm run dist
          node scripts/cp-pkgs.js
          node scripts/verify-pkg-main.js
      - name: Create release
        run: |
          npx lerna version --conventional-commits --no-git-tag-version --no-push --yes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: Publish"
          git tag "v$(npm run version --silent)"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          # TODO: master is a protected branch!
          git push origin master "v$(npm run version --silent)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name:
      - name: Publish to NPM registry
        run: npx lerna publish from-package --yes --dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
